#ifndef E_MOUSE_BUTTON_H
#define E_MOUSE_BUTTON_H

#include <GLFW/glfw3.h>

enum class EMouseButton {
    LEFT = GLFW_MOUSE_BUTTON_LEFT,
    MIDDLE = GLFW_MOUSE_BUTTON_MIDDLE,
    RIGHT = GLFW_MOUSE_BUTTON_RIGHT,
};

#endif //E_MOUSE_BUTTON_H